-- Sprint 31: per-therapist onboarding gate.
--
-- New nullable column on Psychologist set by POST /api/v1/onboarding/complete
-- once the auto-provisioned placeholder fields (email/RCI/fullName) are
-- replaced with real values. Pages guard on this via
-- requireOnboardedPsychologist() — null bounces the user to /app/onboarding.
--
-- Backfill: existing rows that have non-placeholder identity are marked
-- onboarded as of now. The placeholder detection matches the patterns
-- generated by the Sprint 29 auto-provision branch in
-- /api/v1/auth/session.
ALTER TABLE "psychologists"
  ADD COLUMN "onboardingCompletedAt" TIMESTAMP(3);

UPDATE "psychologists"
SET "onboardingCompletedAt" = NOW()
WHERE "email" NOT LIKE '%@unclaimed.cureocity.app'
  AND "phone" NOT LIKE 'pending:%'
  AND "rciNumber" NOT LIKE 'PENDING-%';

CREATE INDEX "psychologists_onboardingCompletedAt_idx"
  ON "psychologists" ("onboardingCompletedAt");
