import {
  type ClinicalLocale,
  type InstrumentKey,
  type PatientShareSnapshot,
  type ShareArtefactRef,
  type TherapyScriptV1,
  TherapyScriptV1Schema,
  type TherapyNoteV1,
  TherapyNoteV1Schema,
  type IntakeNoteV1,
  IntakeNoteV1Schema,
  type MedicalEncounterNoteV1,
  MedicalEncounterNoteV1Schema,
  MedicationOrderV1Schema,
  RxPadV1Schema,
  type ClinicalTreatmentPlan,
  ClinicalTreatmentPlanSchema,
  type SignedIntakeNoteSnapshotSection,
} from '@cureocity/contracts';
import { INSTRUMENTS } from '@cureocity/clinical';
import type { ChronicMeasureKey, ChronicMeasureTrajectory } from '@cureocity/contracts';
import { ProgressReportError, buildProgressReport } from './progress-report';
import { buildChronicTrajectory } from './chronic-trajectory';
import { prisma } from './prisma';

/**
 * Sprint 15 — Snapshot builders.
 *
 * Given a ShareArtefactRef + the requesting psychologist, fetches
 * the source artefact, verifies tenant ownership, and converts it
 * to a discriminated PatientShareSnapshot for storage on the
 * PatientShare row.
 *
 * Each builder is defensive: cross-tenant requests return null +
 * the route returns 404; malformed source JSON throws a typed
 * SnapshotBuildError the route surfaces as a 422.
 *
 * The therapy-script + treatment-plan snapshots intentionally
 * exclude verbatim therapist-facing language (the script steps, the
 * raw plan justifications) — the patient sees a patient-friendly
 * summary and the actionable homework + goals instead.
 */

export class SnapshotBuildError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'SnapshotBuildError';
  }
}

interface BuildArgs {
  ref: ShareArtefactRef;
  clientId: string;
  psychologistId: string;
  language: ClinicalLocale;
}

export interface SnapshotResult {
  snapshot: PatientShareSnapshot;
  subject: string;
  sessionId: string | null;
}

export async function buildSnapshot(args: BuildArgs): Promise<SnapshotResult | null> {
  const result = await dispatchSnapshot(args);
  // CLIN-4 — belt-and-braces: never let mock-fabricated content reach a
  // patient in production. Per-builder [mock] stripping is inconsistent (some
  // builders pass fields raw), so we scan the FINAL snapshot uniformly here
  // and REFUSE rather than launder. In dev/preview the marker is still
  // stripped by stripBracketTag so the mock share flow keeps working.
  if (result) assertNoMockContentInProd(result.snapshot);
  return result;
}

async function dispatchSnapshot(args: BuildArgs): Promise<SnapshotResult | null> {
  switch (args.ref.artefactType) {
    case 'SIGNED_NOTE':
      return buildSignedNote(args, args.ref.sessionId);
    case 'REFLECTION_QUESTIONS':
      return buildReflectionQuestions(args, args.ref.sessionId, args.ref.questions);
    case 'THERAPY_SCRIPT':
      return buildTherapyScript(args, args.ref.therapyScriptId);
    case 'TREATMENT_PLAN':
      return buildTreatmentPlan(args, args.ref.treatmentPlanId);
    case 'PROGRESS_REPORT':
      return buildProgressReportSnapshot(args, args.ref.clientId);
    case 'INSTRUMENT_CHECKIN':
      return buildInstrumentCheckin(args, args.ref.clientId, args.ref.instrumentKey);
    case 'SIGNED_INTAKE_NOTE':
      return buildSignedIntakeNote(args, args.ref.sessionId);
    case 'AFTER_VISIT_SUMMARY':
      return buildAfterVisitSummary(args, args.ref.sessionId);
    case 'CHRONIC_PROGRESS_REPORT':
      return buildChronicProgressReport(args, args.ref.clientId);
    case 'RX_PAD':
      return buildRxPad(args, args.ref.sessionId);
  }
}

/**
 * CLIN-4 — refuse to ship content still carrying the mock backend's `[mock]`
 * marker on a production deployment. This should never fire once the LLM fail-
 * closed guard is in place, but it guarantees no fabricated clinical text ever
 * reaches a patient even if a stale mock-generated row is shared later.
 */
function assertNoMockContentInProd(snapshot: PatientShareSnapshot): void {
  if (process.env['VERCEL_ENV'] !== 'production') return;
  if (/\[mock\]/i.test(JSON.stringify(snapshot))) {
    throw new SnapshotBuildError(
      'Refusing to share content generated by the mock backend. Regenerate this note with the real clinical backend before sharing.',
    );
  }
}

/**
 * Sprint DS5-fu — prescription-pad builder. Deterministic (no LLM): the
 * patient's shareable Rx, built from the SIGNED pad (TherapyNote.rxPad).
 * Gated on the note being signed; only CONFIRMED meds reach the patient
 * (pending/AI-suggested rows are already excluded from the signed pad, and
 * we filter again defensively). Every free-text field is stripped of the
 * [mock] tag before it leaves for a patient.
 */
async function buildRxPad(
  { clientId, psychologistId }: BuildArgs,
  sessionId: string,
): Promise<SnapshotResult | null> {
  const session = await prisma.session.findUnique({
    where: { id: sessionId },
    select: {
      id: true,
      clientId: true,
      psychologistId: true,
      scheduledAt: true,
      therapyNote: { select: { rxPad: true } },
    },
  });
  if (!session || session.psychologistId !== psychologistId || session.clientId !== clientId) {
    return null;
  }
  if (!session.therapyNote) {
    throw new SnapshotBuildError('Cannot share a prescription before the note is signed.');
  }
  if (session.therapyNote.rxPad == null) {
    throw new SnapshotBuildError('No prescription was recorded for this consult.');
  }
  const parsed = RxPadV1Schema.safeParse(session.therapyNote.rxPad);
  if (!parsed.success) {
    throw new SnapshotBuildError('Signed prescription failed schema validation; cannot share.');
  }
  const pad = parsed.data;

  const medications = pad.meds
    .filter((m) => m.status === 'confirmed')
    .map((m) => ({
      line: [
        stripBracketTag(m.drug).trim(),
        m.strength,
        m.dose,
        m.frequency,
        m.timing,
        m.durationDays ? `for ${m.durationDays} days` : null,
      ]
        .filter((p): p is string => !!p && p.length > 0)
        .join(' · '),
      continued: m.continued,
    }))
    .filter((m) => m.line.length > 0);

  const investigations = pad.investigations
    .map((i) => stripBracketTag(i.name).trim())
    .filter((s) => s.length > 0);
  const advice = pad.adviceLines.map((a) => stripBracketTag(a).trim()).filter((s) => s.length > 0);
  const followUp = pad.followUp
    ? [pad.followUp.when, pad.followUp.withWhat].filter(Boolean).join(' · ')
    : '';

  const snapshot: PatientShareSnapshot = {
    kind: 'RX_PAD',
    greeting: 'here is your prescription from today’s visit.',
    diagnosisLine: stripBracketTag(pad.dxLine).trim(),
    medications,
    investigations,
    advice,
    followUp,
  };
  const subject = `Your prescription · ${session.scheduledAt.toLocaleDateString('en-IN', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })}`;
  return { snapshot, subject, sessionId: session.id };
}

/**
 * Sprint DV3 → DV5 — after-visit summary builder. Deterministic (no LLM):
 * a patient-facing recap of the SIGNED medical encounter note — what was
 * discussed + the plan, plus (Sprint DV5) the CONFIRMED medications in
 * plain language. Red-flag extraction is still DV6.
 */
async function buildAfterVisitSummary(
  { clientId, psychologistId }: BuildArgs,
  sessionId: string,
): Promise<SnapshotResult | null> {
  const session = await prisma.session.findUnique({
    where: { id: sessionId },
    select: {
      id: true,
      clientId: true,
      psychologistId: true,
      scheduledAt: true,
      therapyNote: { select: { content: true } },
    },
  });
  if (!session || session.psychologistId !== psychologistId || session.clientId !== clientId) {
    return null;
  }
  if (!session.therapyNote) {
    throw new SnapshotBuildError(
      'Cannot share an after-visit summary before the encounter note is signed.',
    );
  }
  const parsed = MedicalEncounterNoteV1Schema.safeParse(session.therapyNote.content);
  if (!parsed.success) {
    throw new SnapshotBuildError('Signed encounter note failed schema validation; cannot share.');
  }
  const note: MedicalEncounterNoteV1 = parsed.data;
  const cc = stripBracketTag(note.chiefComplaint).trim();

  // Sprint DV5 — confirmed Rx, in plain language. Only CONFIRMED orders
  // reach the patient; drafts the doctor never confirmed are excluded.
  const medRows = await prisma.medicationOrder.findMany({
    where: { sessionId, status: 'CONFIRMED' },
    orderBy: { createdAt: 'asc' },
  });
  const medications = medRows
    .map((row) => {
      const med = MedicationOrderV1Schema.safeParse(row.content);
      if (!med.success) return null;
      const m = med.data;
      const parts = [
        stripBracketTag(m.drug).trim(),
        m.strength,
        m.dose,
        m.frequency,
        m.durationDays ? `for ${m.durationDays} days` : null,
      ].filter((p): p is string => !!p && p.length > 0);
      const line = parts.join(' · ');
      return m.instructions ? `${line} (${stripBracketTag(m.instructions).trim()})` : line;
    })
    .filter((l): l is string => l !== null && l.length > 0);

  const snapshot: PatientShareSnapshot = {
    kind: 'AFTER_VISIT_SUMMARY',
    greeting: 'here is a summary of your visit today.',
    whatWeDiscussed: cc ? [cc] : [],
    medications,
    instructions: splitLines(note.plan),
    followUp: '',
    redFlags: [],
  };
  const subject = `Your visit summary · ${session.scheduledAt.toLocaleDateString('en-IN', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })}`;
  return { snapshot, subject, sessionId: session.id };
}

/**
 * Sprint DV7 — chronic-disease progress report builder. Deterministic (no
 * LLM): turns the per-patient control trajectory into a plain-language,
 * encouraging patient-facing report ("Your blood pressure improved from
 * 150/90 to 130/80 over 8 readings — now within your target"). Verdicts
 * come from the deterministic engine; this only renders them.
 */
const PATIENT_MEASURE_LABEL: Record<ChronicMeasureKey, string> = {
  BP: 'blood pressure',
  HBA1C: 'sugar control (HbA1c)',
  FBS: 'fasting blood sugar',
  LDL: 'cholesterol (LDL)',
  WEIGHT: 'weight',
};

async function buildChronicProgressReport(
  { clientId, psychologistId }: BuildArgs,
  refClientId: string,
): Promise<SnapshotResult | null> {
  if (refClientId !== clientId) {
    throw new SnapshotBuildError('Report clientId does not match the request clientId.');
  }
  const client = await prisma.client.findUnique({
    where: { id: clientId },
    select: { id: true, psychologistId: true, deletedAt: true },
  });
  if (!client || client.psychologistId !== psychologistId || client.deletedAt !== null) {
    return null;
  }
  const trajectory = await buildChronicTrajectory(clientId, psychologistId);
  if (trajectory.measures.length === 0) {
    throw new SnapshotBuildError('No readings recorded yet — nothing to report.');
  }
  const improving = trajectory.measures.filter((m) => m.trend === 'improving').length;
  const headline =
    improving > 0
      ? `Good news — ${improving} of your tracked measures ${improving === 1 ? 'has' : 'have'} improved.`
      : 'Here is how your health numbers are tracking.';
  const snapshot: PatientShareSnapshot = {
    kind: 'CHRONIC_PROGRESS_REPORT',
    greeting: 'here is how your health numbers are tracking.',
    headline,
    measures: trajectory.measures.map(chronicLine),
    encouragement:
      'Keep taking your medicines as advised and keep your follow-up visits — small steps add up.',
  };
  return { snapshot, subject: 'Your health progress report', sessionId: null };
}

function chronicLine(m: ChronicMeasureTrajectory): string {
  const label = PATIENT_MEASURE_LABEL[m.measure];
  const latest = m.latest?.display ?? '';
  const within =
    m.control === 'controlled'
      ? ' — now within your target.'
      : m.control
        ? ` (target ${m.targetText}).`
        : '.';
  if (m.series.length >= 2 && m.baseline) {
    if (m.trend === 'improving') {
      return `Your ${label} improved from ${m.baseline.display} to ${latest} ${m.unit}${within}`;
    }
    if (m.trend === 'worsening') {
      return `Your ${label} needs some attention — it moved from ${m.baseline.display} to ${latest} ${m.unit} (target ${m.targetText}).`;
    }
    return `Your ${label} has stayed steady at ${latest} ${m.unit}${within}`;
  }
  return `Your ${label} is ${latest} ${m.unit}${within}`;
}

/**
 * Sprint 47 — snapshot a PHQ-9 / GAD-7 for self-serve completion.
 *
 * Verifies the client is owned by the requesting therapist, then
 * freezes the instrument's items + scale (in the share language) onto
 * the snapshot so the portal renders the exact validated wording with
 * no clinical-package dependency. The riskItemNumber rides along so
 * the portal can surface crisis resources the moment a self-harm item
 * is endorsed. `completed` starts false; the submit route flips it.
 */
async function buildInstrumentCheckin(
  { clientId, psychologistId, language }: BuildArgs,
  refClientId: string,
  instrumentKey: InstrumentKey,
): Promise<SnapshotResult | null> {
  if (refClientId !== clientId) {
    throw new SnapshotBuildError('Check-in clientId does not match the request clientId.');
  }
  const client = await prisma.client.findUnique({
    where: { id: clientId },
    select: { id: true, psychologistId: true, deletedAt: true },
  });
  if (!client || client.psychologistId !== psychologistId || client.deletedAt !== null) {
    return null;
  }
  const def = INSTRUMENTS[instrumentKey];
  if (!def) {
    throw new SnapshotBuildError(`Unknown instrument: ${instrumentKey}`);
  }
  const pick = <T extends { en: string } & Partial<Record<ClinicalLocale, string>>>(m: T): string =>
    m[language] ?? m.en;
  return {
    snapshot: {
      kind: 'INSTRUMENT_CHECKIN',
      instrumentKey,
      title: pick(def.title),
      recallWindow: pick(def.recallWindow),
      items: def.items.map((i) => ({ id: i.id, number: i.number, text: pick(i.text) })),
      scale: def.scale.map((s) => ({ value: s.value, label: pick(s.label) })),
      riskItemNumber: def.riskItemNumber ?? null,
      completed: false,
      completedAt: null,
    },
    subject: 'A quick check-in before our next session',
    sessionId: null,
  };
}

async function buildSignedNote(
  { clientId, psychologistId }: BuildArgs,
  sessionId: string,
): Promise<SnapshotResult | null> {
  const session = await prisma.session.findUnique({
    where: { id: sessionId },
    select: {
      id: true,
      clientId: true,
      psychologistId: true,
      scheduledAt: true,
      therapyNote: { select: { content: true } },
    },
  });
  if (!session || session.psychologistId !== psychologistId || session.clientId !== clientId) {
    return null;
  }
  if (!session.therapyNote) {
    throw new SnapshotBuildError('Cannot share an unsigned note. Sign the note first.');
  }
  const parsed = TherapyNoteV1Schema.safeParse(session.therapyNote.content);
  if (!parsed.success) {
    throw new SnapshotBuildError('Signed note failed schema validation; cannot share.');
  }
  const note: TherapyNoteV1 = parsed.data;
  const subject = `Your session note · ${session.scheduledAt.toLocaleDateString('en-IN', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })}`;
  return {
    snapshot: {
      kind: 'SIGNED_NOTE',
      // CLIN-4 — route through stripBracketTag like every other builder so a
      // dev/preview [mock] marker is stripped, not shipped verbatim.
      subjective: stripBracketTag(note.subjective),
      objective: stripBracketTag(note.objective),
      assessment: stripBracketTag(note.assessment),
      plan: stripBracketTag(note.plan),
      pdfUrl: null,
    },
    subject,
    sessionId: session.id,
  };
}

/**
 * Sprint 49 — Signed intake note snapshot.
 *
 * Patient-appropriate subset of the intake note: what the client shared
 * + the immediate plan, plus an optional intro section in the
 * therapist's tone. Deliberately excludes mental status exam, working
 * hypothesis, past psychiatric history, family / social history — those
 * carry clinically sensitive content + provisional formulation that
 * needs an explicit clinician sign-off to share, and the patient
 * doesn't need them to act on the plan.
 */
async function buildSignedIntakeNote(
  { clientId, psychologistId }: BuildArgs,
  sessionId: string,
): Promise<SnapshotResult | null> {
  const session = await prisma.session.findUnique({
    where: { id: sessionId },
    select: {
      id: true,
      clientId: true,
      psychologistId: true,
      kind: true,
      scheduledAt: true,
      therapyNote: { select: { content: true } },
    },
  });
  if (!session || session.psychologistId !== psychologistId || session.clientId !== clientId) {
    return null;
  }
  if (session.kind !== 'INTAKE') {
    throw new SnapshotBuildError(
      'SIGNED_INTAKE_NOTE artefact can only be built from an INTAKE session.',
    );
  }
  if (!session.therapyNote) {
    throw new SnapshotBuildError('Cannot share an unsigned intake note. Sign the note first.');
  }
  const parsed = IntakeNoteV1Schema.safeParse(session.therapyNote.content);
  if (!parsed.success) {
    throw new SnapshotBuildError('Signed intake note failed schema validation; cannot share.');
  }
  const note: IntakeNoteV1 = parsed.data;
  const sections: SignedIntakeNoteSnapshotSection[] = [
    {
      title: 'What you shared',
      body: stripBracketTag(note.presentingConcerns),
    },
    {
      title: 'What we agreed to do',
      body: stripBracketTag(note.immediatePlan),
    },
  ];
  const subject = `Your intake summary · ${session.scheduledAt.toLocaleDateString('en-IN', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  })}`;
  return {
    snapshot: {
      kind: 'SIGNED_INTAKE_NOTE',
      sections,
      pdfUrl: null,
    },
    subject,
    sessionId: session.id,
  };
}

async function buildReflectionQuestions(
  { clientId, psychologistId }: BuildArgs,
  sessionId: string,
  questions: string[],
): Promise<SnapshotResult | null> {
  const session = await prisma.session.findUnique({
    where: { id: sessionId },
    select: { id: true, clientId: true, psychologistId: true },
  });
  if (!session || session.psychologistId !== psychologistId || session.clientId !== clientId) {
    return null;
  }
  if (questions.length === 0) {
    throw new SnapshotBuildError('At least one reflection question is required.');
  }
  return {
    snapshot: {
      kind: 'REFLECTION_QUESTIONS',
      questions,
    },
    subject: 'Reflection questions for this week',
    sessionId: session.id,
  };
}

async function buildTherapyScript(
  { clientId, psychologistId, language }: BuildArgs,
  therapyScriptId: string,
): Promise<SnapshotResult | null> {
  const row = await prisma.therapyScript.findUnique({
    where: { id: therapyScriptId },
    select: {
      id: true,
      clientId: true,
      psychologistId: true,
      therapyName: true,
      body: true,
    },
  });
  if (!row || row.psychologistId !== psychologistId || row.clientId !== clientId) {
    return null;
  }
  const parsed = TherapyScriptV1Schema.safeParse(row.body);
  if (!parsed.success) {
    throw new SnapshotBuildError('Therapy script failed schema validation; cannot share.');
  }
  const script: TherapyScriptV1 = parsed.data;
  const patientSummary = composePatientFriendlyScriptSummary(script, language);
  return {
    snapshot: {
      kind: 'THERAPY_SCRIPT',
      therapyName: script.therapyName,
      patientSummary,
      // Sprint 51 — homework loop. assignmentId is null here; the
      // share route mutates the snapshot in-place to inject the
      // ExerciseAssignment id it created before persisting.
      homeworkAssignmentId: null,
      homeworkCompleted: false,
      homeworkCompletedAt: null,
      homework: {
        description: script.homework.description,
        deliveryNotes: script.homework.deliveryNotes,
      },
    },
    subject: `Practice between sessions · ${script.therapyName}`,
    sessionId: null,
  };
}

async function buildTreatmentPlan(
  { clientId, psychologistId }: BuildArgs,
  treatmentPlanId: string,
): Promise<SnapshotResult | null> {
  const row = await prisma.treatmentPlan.findUnique({
    where: { id: treatmentPlanId },
    select: {
      id: true,
      clientId: true,
      psychologistId: true,
      version: true,
      body: true,
      supersededAt: true,
    },
  });
  if (!row || row.psychologistId !== psychologistId || row.clientId !== clientId) {
    return null;
  }
  if (row.supersededAt !== null) {
    throw new SnapshotBuildError(
      'This treatment plan has been superseded by a newer version. Share the active plan instead.',
    );
  }
  const parsed = ClinicalTreatmentPlanSchema.safeParse(row.body);
  if (!parsed.success) {
    throw new SnapshotBuildError('Treatment plan failed schema validation; cannot share.');
  }
  const plan: ClinicalTreatmentPlan = parsed.data;
  return {
    snapshot: {
      kind: 'TREATMENT_PLAN',
      modality: plan.modality,
      phaseSequence: plan.phaseSequence,
      goals: plan.goals,
      expectedDurationSessions: plan.expectedDurationSessions,
    },
    subject: `Your treatment plan · v${row.version}`,
    sessionId: null,
  };
}

/**
 * Sprint 20 — Progress report snapshot builder. Delegates to the
 * deterministic `buildProgressReport` helper, which composes a
 * plain-language pre→post from the cumulative instrument + plan data
 * (no LLM). Cross-tenant access is already enforced inside the
 * helper; we re-check the artefact's clientId matches the route's
 * clientId so a typo in the request body can't share Client A's
 * data into Client B's PatientShare row.
 */
async function buildProgressReportSnapshot(
  args: BuildArgs,
  refClientId: string,
): Promise<SnapshotResult | null> {
  if (refClientId !== args.clientId) {
    throw new SnapshotBuildError('Progress report clientId does not match the request clientId.');
  }
  try {
    const result = await buildProgressReport({
      clientId: args.clientId,
      psychologistId: args.psychologistId,
    });
    return {
      snapshot: result.snapshot,
      subject: result.subject,
      sessionId: null,
    };
  } catch (e) {
    if (e instanceof ProgressReportError) {
      throw new SnapshotBuildError(e.message);
    }
    throw e;
  }
}

/**
 * Strip therapist-facing instructions out of a TherapyScriptV1 so
 * the patient sees an actionable summary — opening intent, what
 * we'll work on, what to expect, homework. Verbatim therapistSays
 * + listenFor + branches stay therapist-only.
 */
function composePatientFriendlyScriptSummary(
  script: TherapyScriptV1,
  _language: ClinicalLocale,
): string {
  const intro = stripBracketTag(script.openingScript);
  const purposes = script.mainExercise.steps
    .slice(0, 5)
    .map((s) => `• ${stripBracketTag(s.purpose)}`);
  const close = stripBracketTag(script.closingScript);
  return [intro, '', 'What we worked on in session:', ...purposes, '', close].join('\n');
}

/**
 * The mock backend prefixes outputs with "[mock]" so we don't ship
 * tagged content to patients. Strip the marker if present.
 */
function stripBracketTag(s: string): string {
  return s.replace(/^\s*\[[A-Za-z0-9_-]+\]\s*/, '');
}

/** Split a free-text plan into readable, patient-facing lines. */
function splitLines(s: string): string[] {
  return stripBracketTag(s)
    .split(/[\n;]+/)
    .map((x) => x.trim())
    .filter((x) => x.length > 0);
}
